baseurl = "http://sourced.tech"
languageCode = "en-us"
title = "Developers"
description = "source{d} is a tech recruiting product build by our technical team for software engineers. Analyzing code contributions in the open source community, we aim for tech recruitment done right."
