title: "source{d}"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"
theme:        ""

metaDataFormat: "yaml"
uglyURLs: false
paginate: 10
paginatePath: "page"

googleAnalytics: ""

disableKinds:
    - RSS
    - Sitemap
enableRobotsTXT: true
enableEmoji: false

watch: true
log: false
verbose: false
verboseLog: false
cleanDestinationDir: true

taxonomies:
    category: "categories"
    class: "classes"

params:
    author: source{d}
    description: "source{d} provides the technology for large-scale code analysis and machine learning on code."
    defaultemail: "hello@sourced.tech"
    location: "San Francisco, Seattle, Madrid & Remote"
    favicon: "img/logos/favicon.png"
    favicon96: "img/logos/favicon96.png"
    socialImage: "img/logos/logo-bg-blue.png"
    pgpLink: "https://keybase.io/sourced"
    social:
        twitter: "sourcedtech"
        github: "src-d"
        linkedin: "sourced"
    # fixed web announcment; if one of its properties is empty, it won't be displayed.
    announcement:
        title: "Watch a 5 minutes video to understand how the engine works"
        url: "https://medium.com/sourcedtech/source-d-engine-in-5-minutes-6b3b19789594"
