title: "source{d}"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"
theme:        ""

metaDataFormat: "yaml"
uglyURLs: false
paginate: 10
paginatePath: "page"

googleAnalytics: ""

disableKinds:
    - RSS
    - Sitemap
enableRobotsTXT: true
enableEmoji: false

watch: true
log: false
verbose: false
verboseLog: false
cleanDestinationDir: true

taxonomies:
    category: "categories"
    class: "classes"

params:
    author: source{d}
    description: "source{d} provides the technology for large-scale code analysis and machine learning on code."
    defaultemail: "hello@sourced.tech"
    location: "San Francisco, Seattle, Madrid & Remote"
    favicon: "img/logos/favicon.png"
    favicon96: "img/logos/favicon96.png"
    pgpLink: "https://keybase.io/sourced"
    headerImageName: alan-turing
    social:
        twitter: "sourcedtech"
        github: "src-d"
        linkedin: "sourced"
        slack:
            orgName: "sourced-community"
            channels:
                languages: "babelfish"
                datasets: "machine-learning"
                models: "machine-learning"
                science: "machine-learning"
                general: "general"
