title: "source{d}"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"
theme:        ""

metaDataFormat: "yaml"
uglyURLs: false
paginate: 10
paginatePath: "page"

googleAnalytics: ""

disableKinds:
    - RSS
    - Sitemap
enableRobotsTXT: true
enableEmoji: false

watch: true
log: false
verbose: false
verboseLog: false
cleanDestinationDir: true

taxonomies:
    category: "categories"
    class: "classes"

params:
    author: source{d}
    description: "Source{d} is the only end to end Engineering Observability platform to provide executives with actionable insights about their codebases, development processes, and teams. Source{d} not only helps enterprises improve their engineering effectiveness and efficiency but also their IT modernization, DevOps Adoption, and Engineering talent management efforts."
    defaultemail: "hello@sourced.tech"
    location: "San Francisco, Seattle, Madrid & Remote"
    favicon: "img/logos/favicon.png"
    favicon96: "img/logos/favicon96.png"
    socialImage: "img/logos/logo-bg-blue.png"
    pgpLink: "https://keybase.io/sourced"
    social:
        twitter: "sourcedtech"
        github: "src-d"
        linkedin: "sourced"
    # fixed web announcment; if one of its properties is empty, it won't be displayed.
    announcement:
        title: "Download our new Machine Learning for Software Development Analytics Ebook"
        url: "https://go.sourced.tech/ml-ebook"
