addr: ":8080"
github-token: "***REMOVED***"
feed-base-url: "http://blog.sourced.tech/json/"
positions-base-url: "https://api.lever.co/v0/postings/sourced?mode=json"
fetcher-page-size: 45
slack-channel: ""
slackin-url: "http://slack.sourced.tech:3000/invite"
repos:
    main:
        - owner: src-d
          repos: [go-git, beanstool, kmcuda, flamingo, hercules, go-siva]
    other:
        - owner: src-d
          repos: [minhashcuda]
        - owner: gitql
          repos: [gitql]
        - owner: erizocosmico
          repos: ['react-categorized-tag-input']
