addr: ":8080"
feed-base-url: "http://blog.sourced.tech/json/"
positions-base-url: "https://api.lever.co/v0/postings/sourced?mode=json"
fetcher-page-size: 45
slack-channel: ""
slackin-url: "http://slackin:3000/invite"
repos:
    main:
        - owner: src-d
          repos: [go-git, kmcuda, proteus, minhashcuda, go-kallax, wmd-relax]
    other:
        - owner: sqle
          repos: [gitquery]
        - owner: hashicorp
          repos: [terraform]
        - owner: tensorflow
          repos: [models]
