addr: ":8080"
github-token: "***REMOVED***"
fetcher-page-size: 45
repos:
    main:
        - owner: src-d
          repos: [go-git, beanstool, kmcuda, flamingo, storable, go-siva]
    other:
        - owner: src-d
          repos: [minhashcuda]
        - owner: gitql
          repos: [gitql]
        - owner: mvader
          repos: ['react-categorized-tag-input']