baseurl: "/"
title: "source{d}"

contentdir:   "hugo/content"
dataDir:      "hugo/data"
layoutdir:    "hugo/layouts"
themesdir:    "hugo/themes"
archetypedir: "hugo/archetype"
destination:  "public"
publishdir:   "public"
staticdir:    "static"
theme:        ""

metaDataFormat: "yaml"
uglyURLs: false
paginate: 10
paginatePath: "page"

googleAnalytics: ""

disableRSS: true
disableSitemap: true
enableRobotsTXT: true
enableEmoji: false

watch: true
log: false
verbose: false
verboseLog: false
cleanDestinationDir: true

taxonomies:
  category: "categories"
  class: "classes"

params:
  author: source{d}
  description: "Building the first AI that understands code"
  copyright: Copyright (c) 2016 source{d}
  location: "Madrid"
  social:
    twitter: "sourced"
    github: "src-d"
    linkedin: "sourced"
